### PR TITLE
feat: add Terraform devcontainer

### LINKED ISSUE #6: Add Terraform devcontainer
Pins version of Terraform for local dev.

### PR DESCRIPTION
**Pull request by patheard**
# Summary
Adds a Terraform devcontainer for local VS Code dev work.

Closes #6

### CODE REVIEW

**Comment by CalvinRodo** [comment]
This needs to support docker containers being run alongside the devcontainer. 

We use docker to run the following scripts: 

- https://github.com/cds-snc/terraform-modules/blob/feat/multiple_accounts_readme/bin/generate-docs.sh
- https://github.com/cds-snc/terraform-modules/tree/feat/multiple_accounts_readme/.github/workflows/scripts/run-shellcheck.sh

They no longer with this devcontainer meaning we'd have to leave the container to generate docs.

**Review by CalvinRodo — CHANGES_REQUESTED** [review]
This needs to support docker containers being run alongside the devcontainer. 

We use docker to run the following scripts: 

- https://github.com/cds-snc/terraform-modules/blob/feat/multiple_accounts_readme/bin/generate-docs.sh
- https://github.com/cds-snc/terraform-modules/tree/feat/multiple_accounts_readme/.github/workflows/scripts/run-shellcheck.sh

They no longer with this devcontainer meaning we'd have to leave the container to generate docs.

**Comment by patheard** [comment]
I'll get shellcheck and the terraform-docs tools installed in the devcontainer.

**Review by CalvinRodo — APPROVED** [review]
:taco::cat:

**Pull request merged**
